config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'static_pages/home'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase } #downcases email adresses before saving them

  validates :first_name, presence: true
  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }

  has_secure_password
validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # Returns the hash digest of the given string.
def User.digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
   @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
   @user = User.new(user_params)
   if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to user_url(@user)
   else
     render 'new'
   end
 end

 def index
 end

 def edit
   @user = User.find(params[:id])
   (flash[:success] = "You can't edit another's profile !"
   redirect_to(root_url) ) unless @user == current_user
 end

 def update
  @user = User.find(params[:id])
  if @user.update_attributes(user_params)
    flash[:success] = "Profile updated"
    redirect_to @user
  else
    render 'edit'
  end
end

   private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password,
                                   :password_confirmation)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
  session.delete(:user_id)
  @current_user = nil
end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Mon Club", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "Index", users_path %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li> <%= link_to "Log out", logout_path, method: :delete %>  </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mon Club</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <header><%= render 'layouts/header' %></header>
     <div class="container">
         <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>



</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Mon Club</h1>

  <h2>
    This is the home page for the most private of private clubs.
  </h2>

  <% if logged_in? %>
    <%= link_to "Members index", users_path, class: "btn btn-lg btn-primary" %>
  <% else %>
  You need to be logged in to access the club's members' list. <br><br>
    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>     <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if logged_in? %>

<!-- Edit form if it's the right user -->
  <% if @user == current_user%>

  <br> <br>
  <h1>Update your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>

  <% end %>

  <% else %>
  You need to be logged in to access the club's members' list. <br><br>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>     <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>

<% end %>

app/views/users/index.html.erb
<% if logged_in? %>

    <% User.all.each_with_index do |user, index| %>
        <p>
          <div class="card" style="width: 18rem;">
          <h5 class="card-title"><%=user.first_name%> <%=user.last_name%></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%=user.email%></h6>
          <%= link_to "profile page", user_url(user)%>
        </div>
        </p>
      <% end %>

<% else %>
  You need to be logged in to access the club's members' list. <br><br>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>     <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>

<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

  <div class="col-md-5 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>

<% if logged_in? %>

  <h1>
  <%= @user.first_name %>, <%= @user.last_name %>
  </h1>

  <%= @user.email %>

  <% if @user == current_user%>
  <br> <br>
  <%= link_to "Edit profile", edit_user_path %>
  <% end %>

<% else %>
  You need to be logged in to access this content. <br><br>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>     <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>

<% end %>